"""
Split the cleaned Cube YOLOv8 dataset into train/valid/test.

This script assumes labels have already been cleaned to 4 classes:
0 Cube_food, 1 Cube_ins, 2 Cube_medicine, 3 Cube_tool.
It copies files into Cube.yolov8/split and recreates that directory on
each run so stale files from older datasets cannot remain.
"""

import os
import random
import shutil
import sys
from collections import Counter
from pathlib import Path


sys.stdout.reconfigure(encoding="utf-8")

SEED = 42
TRAIN_RATIO = 0.80
VALID_RATIO = 0.10
ALLOWED_CLASSES = {0, 1, 2, 3}
CLASS_NAMES = ["Cube_food", "Cube_ins", "Cube_medicine", "Cube_tool"]

BASE = Path(__file__).resolve().parent
CUBE = BASE / "Cube.yolov8"
SRC_IMAGES = CUBE / "train" / "images"
SRC_LABELS = CUBE / "train" / "labels"
SPLIT = CUBE / "split"


def image_files():
    return sorted(
        f
        for f in os.listdir(SRC_IMAGES)
        if f.lower().endswith((".jpg", ".jpeg", ".png"))
    )


def label_name_for(image_name):
    return Path(image_name).with_suffix(".txt").name


def read_class_ids(label_path):
    class_ids = []
    with open(label_path, "r", encoding="utf-8-sig") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            class_ids.append(int(float(line.split()[0])))
    return class_ids


def copy_pair(image_name, split_name):
    label_name = label_name_for(image_name)
    src_image = SRC_IMAGES / image_name
    src_label = SRC_LABELS / label_name
    dst_image = SPLIT / split_name / "images" / image_name
    dst_label = SPLIT / split_name / "labels" / label_name

    if not src_label.exists():
        raise FileNotFoundError(f"Missing label for {image_name}: {label_name}")

    shutil.copy2(src_image, dst_image)
    shutil.copy2(src_label, dst_label)


def validate_pairs(files):
    missing = []
    for image_name in files:
        if not (SRC_LABELS / label_name_for(image_name)).exists():
            missing.append(image_name)
    if missing:
        raise RuntimeError(f"Missing labels for {len(missing)} images: {missing[:5]}")


def validate_classes(files):
    counts = Counter()
    bad_classes = Counter()
    for image_name in files:
        label_path = SRC_LABELS / label_name_for(image_name)
        for class_id in read_class_ids(label_path):
            counts[class_id] += 1
            if class_id not in ALLOWED_CLASSES:
                bad_classes[class_id] += 1
    if bad_classes:
        raise RuntimeError(f"Found unexpected class ids: {dict(sorted(bad_classes.items()))}")
    return counts


def validate_split(split_files):
    all_images = []
    for split_name, expected_files in split_files.items():
        img_dir = SPLIT / split_name / "images"
        lbl_dir = SPLIT / split_name / "labels"
        imgs = sorted(f.name for f in img_dir.iterdir() if f.is_file())
        lbls = sorted(f.stem for f in lbl_dir.iterdir() if f.is_file())
        img_stems = sorted(Path(f).stem for f in imgs)

        if img_stems != lbls:
            raise RuntimeError(f"{split_name} image/label mismatch")
        if sorted(expected_files) != imgs:
            raise RuntimeError(f"{split_name} copied file list mismatch")
        all_images.extend(imgs)

        split_counts = Counter()
        for label_file in lbl_dir.glob("*.txt"):
            split_counts.update(read_class_ids(label_file))
        print(
            f"{split_name}: {len(imgs)} images, {len(lbls)} labels, "
            f"classes={dict(sorted(split_counts.items()))}"
        )

    if len(all_images) != len(set(all_images)):
        raise RuntimeError("Duplicate image names found across splits")


def write_yaml():
    yaml_content = f"""# Cube dataset split - 80/10/10 with seed={SEED}
# Generated by split_data.py

path: split
train: train/images
val: valid/images
test: test/images

nc: 4
names: {CLASS_NAMES}
"""
    yaml_path = CUBE / "data_split.yaml"
    yaml_path.write_text(yaml_content, encoding="utf-8")
    return yaml_path


def main():
    files = image_files()
    if not files:
        raise RuntimeError(f"No images found in {SRC_IMAGES}")

    validate_pairs(files)
    class_counts = validate_classes(files)

    rng = random.Random(SEED)
    shuffled = list(files)
    rng.shuffle(shuffled)

    n_total = len(shuffled)
    n_train = int(n_total * TRAIN_RATIO)
    n_valid = int(n_total * VALID_RATIO)
    split_files = {
        "train": shuffled[:n_train],
        "valid": shuffled[n_train : n_train + n_valid],
        "test": shuffled[n_train + n_valid :],
    }

    print(f"Total images: {n_total}")
    print(f"Class counts: {dict(sorted(class_counts.items()))}")
    print(
        "Split counts: "
        f"train={len(split_files['train'])}, "
        f"valid={len(split_files['valid'])}, "
        f"test={len(split_files['test'])}"
    )

    if SPLIT.exists():
        shutil.rmtree(SPLIT)
    for split_name in split_files:
        (SPLIT / split_name / "images").mkdir(parents=True, exist_ok=True)
        (SPLIT / split_name / "labels").mkdir(parents=True, exist_ok=True)

    for split_name, names in split_files.items():
        for image_name in names:
            copy_pair(image_name, split_name)

    validate_split(split_files)
    yaml_path = write_yaml()

    print(f"Wrote {yaml_path}")
    print("All checks passed.")


if __name__ == "__main__":
    main()
