"""
Data split script for Cube dataset.
Splits 343 images into train/valid/test at 80/10/10 with seed=42.
Copies files (does not move originals).
"""
import os
import sys
import shutil
import random
from pathlib import Path

# Force UTF-8 output on Windows
sys.stdout.reconfigure(encoding='utf-8')

random.seed(42)

# Paths
BASE = Path(r"e:/xwechat_files/wxid_el79rox3ahjk12_09c9/msg/file/2026-05/yolo_gsing")
CUBE = BASE / "Cube.yolov8"
SRC_IMAGES = CUBE / "train" / "images"
SRC_LABELS = CUBE / "train" / "labels"
SPLIT = CUBE / "split"

# Ratios
TRAIN_RATIO = 0.80
VALID_RATIO = 0.10
TEST_RATIO = 0.10

# Gather all image files (strip extensions to get base names)
image_files = sorted([f for f in os.listdir(SRC_IMAGES) if f.lower().endswith(('.jpg', '.jpeg', '.png'))])
random.shuffle(image_files)

n = len(image_files)
n_train = int(n * TRAIN_RATIO)
n_valid = int(n * VALID_RATIO)
# n_test gets the remainder to ensure exact total

train_files = image_files[:n_train]
valid_files = image_files[n_train:n_train + n_valid]
test_files = image_files[n_train + n_valid:]

print(f"Total images: {n}")
print(f"Train: {len(train_files)}")
print(f"Valid: {len(valid_files)}")
print(f"Test:  {len(test_files)}")
print(f"Sum:   {len(train_files) + len(valid_files) + len(test_files)}")

# Create directories
for split_name in ["train", "valid", "test"]:
    for sub in ["images", "labels"]:
        (SPLIT / split_name / sub).mkdir(parents=True, exist_ok=True)

# Copy function
def copy_files(file_list, src_dir, dst_dir):
    for fname in file_list:
        shutil.copy2(src_dir / fname, dst_dir / fname)

# Copy images
print("\nCopying images...")
copy_files(train_files, SRC_IMAGES, SPLIT / "train" / "images")
copy_files(valid_files, SRC_IMAGES, SPLIT / "valid" / "images")
copy_files(test_files, SRC_IMAGES, SPLIT / "test" / "images")

# Copy corresponding labels
print("Copying labels...")
for split_name, file_list in [("train", train_files), ("valid", valid_files), ("test", test_files)]:
    dst_labels = SPLIT / split_name / "labels"
    for fname in file_list:
        # Replace image extension with .txt
        base = os.path.splitext(fname)[0]
        label_name = base + ".txt"
        src_label = SRC_LABELS / label_name
        if src_label.exists():
            shutil.copy2(src_label, dst_labels / label_name)
        else:
            print(f"  WARNING: No label found for {fname} (expected {label_name})")

# Validate
print("\n=== Validation ===")
all_ok = True
for split_name in ["train", "valid", "test"]:
    img_dir = SPLIT / split_name / "images"
    lbl_dir = SPLIT / split_name / "labels"
    imgs = set(os.path.splitext(f)[0] for f in os.listdir(img_dir))
    lbls = set(os.path.splitext(f)[0] for f in os.listdir(lbl_dir))
    missing_labels = imgs - lbls
    extra_labels = lbls - imgs
    print(f"{split_name}: {len(imgs)} images, {len(lbls)} labels")
    if missing_labels:
        print(f"  MISSING labels for: {missing_labels}")
        all_ok = False
    if extra_labels:
        print(f"  EXTRA labels: {extra_labels}")
        all_ok = False

# Check class labels are only 0,1,2,3
print("\n=== Class Label Check ===")
for split_name in ["train", "valid", "test"]:
    lbl_dir = SPLIT / split_name / "labels"
    bad_classes = set()
    for fname in os.listdir(lbl_dir):
        with open(lbl_dir / fname) as f:
            for line in f:
                line = line.strip()
                if line:
                    cls = int(float(line.split()[0]))
                    if cls not in (0, 1, 2, 3):
                        bad_classes.add(cls)
    if bad_classes:
        print(f"  {split_name}: BAD CLASSES {bad_classes}")
        all_ok = False
    else:
        print(f"  {split_name}: all classes in [0,1,2,3] ✓")

# Check for duplicates across splits
print("\n=== Cross-Split Duplicate Check ===")
train_set = set(os.listdir(SPLIT / "train" / "images"))
valid_set = set(os.listdir(SPLIT / "valid" / "images"))
test_set = set(os.listdir(SPLIT / "test" / "images"))
overlap_tv = train_set & valid_set
overlap_tt = train_set & test_set
overlap_vt = valid_set & test_set
if overlap_tv or overlap_tt or overlap_vt:
    print(f"  DUPLICATES FOUND: tv={overlap_tv}, tt={overlap_tt}, vt={overlap_vt}")
    all_ok = False
else:
    print("  No duplicates across splits ✓")

total_split = len(train_set) + len(valid_set) + len(test_set)
print(f"\nTotal in split: {total_split} (expected 343)")
if total_split != 343:
    print("  WARNING: count mismatch!")
    all_ok = False

# Write data_split.yaml
yaml_content = f"""# Cube dataset split - 80/10/10 with seed=42
# Generated by split_data.py

path: {SPLIT.as_posix()}
train: train/images
val: valid/images
test: test/images

nc: 4
names: ['Cube_food', 'Cube_ins', 'Cube_medicine', 'Cube_tool']
"""
yaml_path = CUBE / "data_split.yaml"
with open(yaml_path, "w") as f:
    f.write(yaml_content)
print(f"\nWrote {yaml_path}")

if all_ok:
    print("\n✓ All checks passed!")
else:
    print("\n✗ Some checks failed - review above warnings.")
